# Upload
jk_media.media.upload:
    path: /media/upload
    methods: [post]
    controller: JK\MediaBundle\Action\Upload\EndpointAction

# Media Modal
media.add_image_modal:
    path: /media/add-image
    controller: JK\MediaBundle\Action\TinyMce\GetImageModal

media.edit_image_modal:
    path: /media/edit-image
    controller: JK\MediaBundle\Action\TinyMce\GetImageModal

jk_media.media.select:
    path: /media/select
    controller: JK\MediaBundle\Action\Media\SelectAction

# Media Gallery
media.gallery_modal:
    path: /media/gallery/modal
    controller: JK\MediaBundle\Action\Gallery\ModalAction

media.gallery:
    path: /media/gallery/render
    controller: JK\MediaBundle\Action\Gallery\RenderAction
