jk_media.tinymce.add_media:
    path: /media/tinymce/add
    controller: JK\MediaBundle\Action\Media\TinyMceAddAction

jk_media.tinymce.update_media:
    path: /media/tinymce/add
    controller: JK\MediaBundle\Action\Media\TinyMceUpdateAction

jk_media.tinymce.gallery:
    path: /media/tinymce/gallery
    controller: JK\MediaBundle\Action\Media\GalleryAction


## TODO to remove ?
# Media Modal
media.add_image_modal:
    path: /media/add-image
    controller: JK\MediaBundle\Action\TinyMce\GetImageModal

media.edit_image_modal:
    path: /media/edit-image
    controller: JK\MediaBundle\Action\TinyMce\GetImageModal

# Media Upload
media.upload_ajax:
    path: /media/upload-ajax
    controller: JK\MediaBundle\Action\Media\UploadMediaAjaxAction

# Media Gallery
media.gallery_modal:
    path: /media/gallery/modal
    controller: JK\MediaBundle\Action\Gallery\ModalAction

media.gallery.content:
    path: /media/gallery/content
    controller: JK\MediaBundle\Action\Gallery\ShowGalleryAction
