services:
    JK\MediaBundle\Assets\Path\PublicPathResolverInterface: '@JK\MediaBundle\Assets\Path\PublicPathResolver'
    JK\MediaBundle\Assets\Path\PublicPathResolver:
        arguments:
            $cacheManager: '@liip_imagine.cache.manager'
