parameters:
    media.upload_directory: '%kernel.project_dir%/public/uploads'

services:
    JK\MediaBundle\Action\TinyMce\GetUpdateModal:
        class: JK\MediaBundle\Action\TinyMce\GetUpdateModal
        tags:
            - 'controller.service_arguments'
        arguments:
            $environment: '@twig'
            $formFactory: '@form.factory'

    JK\MediaBundle\Action\TinyMce\GetImageModal:
        class: JK\MediaBundle\Action\TinyMce\GetImageModal
        tags:
            - 'controller.service_arguments'
        arguments:
            $environment: '@twig'
            $formFactory: '@form.factory'
            $handler: '@JK\MediaBundle\Handler\Form\AddImageHandler'

    JK\MediaBundle\Action\Media\UploadMediaAjaxAction:
        class: JK\MediaBundle\Action\Media\UploadMediaAjaxAction
        tags:
            - 'controller.service_arguments'
        arguments:
            $uploader: '@JK\MediaBundle\Upload\Uploader\UploaderInterface'
            $helper: '@JK\MediaBundle\Assets\Helper\AssetsHelper'

    JK\MediaBundle\Action\Gallery\ShowGalleryAction:
        class: JK\MediaBundle\Action\Gallery\ShowGalleryAction
        tags:
            - 'controller.service_arguments'
        arguments:
            $environment: '@twig'
            $repository: '@JK\MediaBundle\Repository\MediaRepository'

    JK\MediaBundle\Action\Gallery\ModalAction:
        tags:
            - 'controller.service_arguments'
        arguments:
            $environment: '@Twig\Environment'
            $formFactory: '@Symfony\Component\Form\FormFactoryInterface'
            $repository: '@JK\MediaBundle\Repository\MediaRepository'
            $handler: '@JK\MediaBundle\Handler\Form\Tinymce\AddGalleryHandler'
