services:
    JK\MediaBundle\DataSource\DataSourceInterface:
        class: JK\MediaBundle\DataSource\CompositeDataSource
        arguments:
            $dataSources: !tagged_iterator {tag: jk_media.datasource, index_by: datasource_name}

    JK\MediaBundle\DataSource\UploadDataSource:
        arguments:
            $uploader: '@JK\MediaBundle\Upload\Uploader\UploaderInterface'
            $mediaRepository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
        tags: [{name: jk_media.datasource, datasource_name: upload, priority: -255}]
