services:
    ### Form Types ###
    JK\MediaBundle\Form\Type\MediaType:
        arguments:
            $transformer: '@JK\MediaBundle\Form\Transformer\MediaTransformer'
        tags: ['form.type']

#    JK\MediaBundle\Form\Type\TinyMceType:
#        tags: ['form.type']

    JK\MediaBundle\Form\Type\SelectType:
        tags: ['form.type']

    JK\MediaBundle\Form\Type\GalleryType:
        arguments:
            $mediaRepository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
            $requestStack: '@Symfony\Component\HttpFoundation\RequestStack'
        tags:
            - {name: form.type}

    ### Form Handlers ###
    JK\MediaBundle\Form\Handler\SelectFormHandlerInterface: '@JK\MediaBundle\Form\Handler\SelectFormHandler'
    JK\MediaBundle\Form\Handler\SelectFormHandler:
        arguments:
            $uploader: '@JK\MediaBundle\Upload\UploaderInterface'
            $mediaRepository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'

    ### Transformers ###
    JK\MediaBundle\Form\Transformer\MediaTransformer:
        arguments:
            $repository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
