services:
    ### Form Types ###
    JK\MediaBundle\Form\Type\MediaType:
        arguments:
            $router: '@router'
        tags: ['form.type']

    JK\MediaBundle\Form\Type\TinyMceType:
        tags: ['form.type']

    JK\MediaBundle\Form\Type\SelectType:
        tags: ['form.type']

    JK\MediaBundle\Form\Type\MediaUploadType:
        tags:
            - {name: form.type}

    JK\MediaBundle\Form\Type\UploadType:
        arguments:
            $router: '@router'
        tags: [form.type]

    JK\MediaBundle\Form\Type\GalleryType:
        arguments:
            $mediaRepository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
            $requestStack: '@Symfony\Component\HttpFoundation\RequestStack'
        tags:
            - {name: form.type}

#    JK\MediaBundle\Form\Type\DataSourceCollectionType:
#        arguments:
#            $dataSourceTypes: [] # see compiler pass
#        tags: ['form.type']

    ### Form Handlers ###
    JK\MediaBundle\Form\Handler\SelectFormHandlerInterface: '@JK\MediaBundle\Form\Handler\SelectFormHandler'
    JK\MediaBundle\Form\Handler\SelectFormHandler:
        $uploader: '@JK\MediaBundle\Upload\Uploader\UploaderInterface'
        $mediaRepository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
