services:
    ### Form Types ###
    JK\MediaBundle\Form\Type\MediaType:
        arguments:
            $router: '@router'
        tags: ['form.type']

    JK\MediaBundle\Form\Type\TinyMceType:
        tags: ['form.type']

    JK\MediaBundle\Form\Type\MediaSelectType:
        arguments:
            $dataSources: '@JK\MediaBundle\DataSource\DataSourceRegistryInterface'
        tags: ['form.type']

    ### Form Transformers ###
    JK\MediaBundle\Form\Transformer\JQueryUploadTransformer:
        class: JK\MediaBundle\Form\Transformer\JQueryUploadTransformer
        arguments:
            - '@JK\MediaBundle\Repository\MediaRepository'
            - '@JK\MediaBundle\Factory\MediaFactory'

    JK\MediaBundle\Form\Transformer\MediaTransformer:
        class: JK\MediaBundle\Form\Transformer\MediaTransformer
        arguments:
            - '@JK\MediaBundle\Repository\MediaRepository'
            - '@JK\MediaBundle\Factory\MediaFactory'

