services:
    ### Form Types ###
#    JK\MediaBundle\Form\Type\JQueryUploadType:
#        class: JK\MediaBundle\Form\Type\JQueryUploadType
#        arguments:
#            - '@oneup_uploader.templating.uploader_helper'
#            - '@JK\MediaBundle\Form\Transformer\JQueryUploadTransformer'
#        tags:
#            - {name: form.type}

    JK\MediaBundle\Form\Type\MediaType:
        arguments:
            - '@JK\MediaBundle\Form\Transformer\MediaTransformer'
            - '@router'
        tags:
            - {name: form.type}

    JK\MediaBundle\Form\Type\TinyMceType:
        tags:
            - {name: form.type}

    ### Form Transformers ###
    JK\MediaBundle\Form\Transformer\JQueryUploadTransformer:
        class: JK\MediaBundle\Form\Transformer\JQueryUploadTransformer
        arguments:
            - '@JK\MediaBundle\Repository\MediaRepository'
            - '@JK\MediaBundle\Factory\MediaFactory'

    JK\MediaBundle\Form\Transformer\MediaTransformer:
        class: JK\MediaBundle\Form\Transformer\MediaTransformer
        arguments:
            - '@JK\MediaBundle\Repository\MediaRepository'
            - '@JK\MediaBundle\Factory\MediaFactory'

