services:
    JK\MediaBundle\Handler\Form\AddImageHandler:
        arguments:
            $environment: '@Twig\Environment'
            $repository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
            $uploader: '@JK\MediaBundle\Upload\Uploader\UploaderInterface'

    JK\MediaBundle\Handler\Form\Tinymce\AddGalleryHandler:
        arguments:
            $environment: '@Twig\Environment'
            $repository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
