#services:
#    JK\MediaBundle\Upload\Handler\MediaHandlerInterface: '@JK\MediaBundle\Upload\Handler\CompositeHandler'
#    JK\MediaBundle\Upload\Handler\CompositeHandler:
#        arguments:
#            $handlers: !tagged_iterator media.handler
#
#    JK\MediaBundle\Upload\Handler\GalleryHandler:
#        arguments:
#            $mediaRepository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
#        tags:
#            - {name: media.handler, priority: 0}
