services:
    JK\MediaBundle\Media\Handler\MediaHandlerInterface: '@JK\MediaBundle\Media\Handler\CompositeHandler'
    JK\MediaBundle\Media\Handler\CompositeHandler:
        arguments:
            $handlers: !tagged_iterator media.handler

    JK\MediaBundle\Media\Handler\GalleryHandler:
        arguments:
            $mediaRepository: '@JK\MediaBundle\Repository\MediaRepositoryInterface'
        tags:
            - {name: media.handler, priority: 0}
