services:
    JK\MediaBundle\Assets\Helper\AssetsHelper:
        arguments:
            $kernelEnvironment: '%kernel.environment%'
            $rootDirectory: '%kernel.root_dir%'
            $assetsMapping: '%jk_media.mapping%'
            $router: '@Symfony\Component\Routing\RouterInterface'
            $assetsManager: '@liip_imagine.cache.manager'
            $uploader: '@JK\MediaBundle\Upload\Uploader\UploaderInterface'
