services:
    JK\MediaBundle\Repository\MediaRepository:
        arguments:
            $registry: '@doctrine'

    JK\MediaBundle\Repository\MediaRepositoryInterface: '@JK\MediaBundle\Repository\MediaRepository'
