services:
    JK\MediaBundle\Twig\Extension\MediaExtension:
        arguments:
            $pathResolver: '@JK\MediaBundle\Assets\Path\MediaPathResolverInterface'
        tags:
            - {name: twig.extension}
