services:
    JK\MediaBundle\Upload\Path\PathResolverInterface: '@JK\MediaBundle\Upload\Path\PathResolver'
    JK\MediaBundle\Upload\Path\PathResolver:
        arguments:
            $mapping: '%jk_media.mapping%'

    JK\MediaBundle\Upload\Uploader\UploaderInterface: '@JK\MediaBundle\Upload\Uploader\Uploader'
    JK\MediaBundle\Upload\Uploader\Uploader:
        class: JK\MediaBundle\Upload\Uploader\Uploader
        autowire: true
        arguments:
            $publicPath: '%jk_media.public_path%'
            $pathResolver: '@JK\MediaBundle\Upload\Path\PathResolverInterface'
            $mediaStorage: '@media.storage'
            $eventDispatcher: '@event_dispatcher'
