services:
    JK\MediaBundle\Upload\Path\RelativePathResolverInterface: '@JK\MediaBundle\Upload\Path\RelativePathResolver'
    JK\MediaBundle\Upload\Path\RelativePathResolver:
        arguments:
            $mapping: '%jk_media.mapping%'

    JK\MediaBundle\Upload\UploaderInterface: '@JK\MediaBundle\Upload\Uploader'
    JK\MediaBundle\Upload\Uploader:
        autowire: true
        arguments:
            $pathGenerator: '@JK\MediaBundle\Path\Generator\PathGeneratorInterface'
            $mediaStorage: '@jk_media.storage'
            $eventDispatcher: '@event_dispatcher'
