version: '3.5'

services:
    php:
        build:
            context: .
        environment:
            DATABASE_URL: mysql://media:media@db/media
        volumes:
            - ./src:/var/www/app/bundle/src
            - ./.docker/app:/var/www/app
            - ./tests/fixtures/app/src/Controller:/var/www/app/src/Controller
            - ./tests/fixtures/app/config/routes.yaml:/var/www/app/config/routes.yaml
            - ./tests/fixtures/app/templates:/var/www/app/templates
            - ./tests/fixtures/app/entrypoint.sh:/usr/bin/entrypoint.sh
        command: /usr/bin/entrypoint.sh
        ports:
            - '8000:8000'
        depends_on:
            - db

    db:
        image: mariadb:10.5
        volumes:
            - ./.docker/mysql/media:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: 'password'
            MARIADB_DATABASE: media
            MARIADB_USER: media
            MARIADB_PASSWORD: media
        ports:
            - '3306:3306'
