name: MediaBundle Tests

on:
    - push

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        env:
            extensions: json
            composer_version: 2
        strategy:
            matrix:
                php_version:
                    - '8.0'
        steps:
            -   uses: actions/checkout@v2
            
            -   name: Cache vendors
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.composer/cache
                    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
            
            -   name: Setup PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    extensions: ${{ env.extensions }}
                    ini-values: memory_limit=-1
                    coverage: pcov
                    tools: composer, php-cs-fixer, cs2pr
            
            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Fix bug in CI
                run: composer require symfony/translation

            -   name: Install yarn dependencies
                run: yarn install --force

            -   name: Build yarn dependencies
                run: yarn run encore production
            
            -   name: Run phpunit
                run: make phpunit.run
            
            -   name: Run php-cs-fixer
                run: make php-cs-fixer.ci
            
            -   name: Run phpstan
                run: make phpstan.run
            
            -   name: Upload code coverage to Scrutinizer CI
                run: |
                    wget https://scrutinizer-ci.com/ocular.phar
                    php ocular.phar code-coverage:upload --format=php-clover var/phpunit/logs/clover.xml
